planning_node:
  ros__parameters:
    x_min_m: 0.0
    x_max_m: 0.31
    y_min_m: -0.25
    y_max_m: 0.25
    ipm_width: 400.0
    ipm_height: 320.0
    origin_offset_x_m: 0.0      # 필요하면 여기서 조금씩 조정
    origin_offset_y_m: -0.05    # 예: 오른쪽으로 5cm 차이 있을 때
